Repository NVIDIA/Bobber, pull requests merged in 2021-05, with the labels that each got.

#59 Upgrade Imageinary version
  bobber/lib/docker/Dockerfile
  bobber/test_scripts/dali_multi.sh
Labels: enhancement

#76 Fix issue creating TFRecords
  bobber/test_scripts/dali_multi.sh
Labels: bug, tests

#75 Add CI support via GitLab
  .gitlab-ci.yml
  bobber/lib/constants.py
Labels: ci/cd, enhancement

#57 Release version 6.2.0
  README.md
  bobber/__version__.py
  bobber/lib/analysis/common.py
  docs/building.md
  docs/troubleshooting.md
Labels: release

#78 Underlying dependency removed its dependency on six - adding for bobber
  setup.py
Labels: bug, ci/cd

#79 Release version 6.3.0
  README.md
  bobber/__version__.py
  bobber/lib/analysis/common.py
  docs/building.md
  docs/troubleshooting.md
Labels: release

#67 Allow for random IO workloads via fio - default to sequential
  .gitlab-ci.yml
  bobber/bobber.py
  bobber/lib/analysis/common.py
  bobber/lib/constants.py
  bobber/lib/tests/run_tests.py
  bobber/test_scripts/fio_multi.sh
Labels: enhancement
