Repository NVIDIA/Bobber, pull requests merged in 2021-04, with the labels that each got.

#62 Optionally save JSON data from parser
  bobber/bobber.py
  bobber/lib/analysis/parse_results.py
Labels: enhancement, parser

#64 Remove nccl-max default from parser
  bobber/bobber.py
Labels: bug, commands

#72 Fix filename for fio IOPs test
  bobber/lib/tests/run_tests.py
Labels: bug
