Repository NVIDIA/Bobber, pull requests merged in 2021-02, with the labels that each got.

#4 Support GitHub Actions
  .github/workflows/python-package.yml
Labels: enhancement

#6 Add verbose flag to results parser
  bobber/bobber.py
  bobber/lib/analysis/parse_results.py
  docs/parsing.md
Labels: enhancement

#13 Docker.md -> docker.md, update README
  README.md
  docs/docker.md
Labels: documentation

#22 Remove memory restriction in containers
  bobber/lib/docker/management.py
Labels: bug, tests

#24 Update wheel metadata information
  setup.py
Labels: bug

#21 Handle situations where no logs are found
  bobber/lib/analysis/parse_results.py
Labels: bug, parser

#17 Add a custom baseline config tool
  README.md
  bobber/bobber.py
  bobber/lib/analysis/compare_baseline.py
  bobber/lib/analysis/parse_results.py
  bobber/lib/system/file_handler.py
  docs/baselines.md
  docs/sample_baseline.yaml
  requirements.txt
  setup.py
Labels: enhancement, parser

#18 Remove unused commands
  README.md
  bobber/bobber.py
  bobber/lib/constants.py
  bobber/lib/tests/run_tests.py
Labels: bug, commands

#27 Add --version flag
  bobber/bobber.py
Labels: enhancement

#23 Add documentation on building from source
  build-dev-wheel
  docs/building.md
Labels: documentation, enhancement

#29 Update MLPerf RN50 parser to show filesystem path under test
  bobber/lib/analysis/parse-mlperf.py
Labels: enhancement, parser

#30 Release version 6.1.0
  bobber/__version__.py
Labels: release

#32 Fix issue running all tests with latest release
  bobber/lib/tests/run_tests.py
Labels: bug, commands

#34 Update mlperf parser path in docs
  docs/parsing.md
Labels: documentation, parser

#37 Adding nosec flag to skip unjustified security error
  bobber/lib/analysis/common.py
Labels: enhancement

#36 Release version 6.1.1
  README.md
  bobber/__version__.py
  docs/building.md
Labels: release

#25 Add documentation on common exit statuses
  bobber/lib/analysis/compare_baseline.py
  bobber/lib/analysis/parse_results.py
  bobber/lib/docker/management.py
  bobber/lib/exit_codes.py
  docs/troubleshooting.md
Labels: documentation

#41 Parse mdtest results
  bobber/lib/analysis/aggregate_results.py
  bobber/lib/analysis/meta.py
  bobber/lib/analysis/parse_results.py
Labels: enhancement, parser
